name: Android CI

on:
  push:
    branches: [ main, starter ]
  pull_request:
    branches: [ main, starter ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
          
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper
          
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          ndk-version: '25.1.8937393'
          cmake-version: '3.22.1'
          
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        shell: bash
        
      - name: Build with Gradle
        run: |
          ./gradlew assembleDebug
          ./gradlew test
        shell: bash
        
      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: apk-artifacts
          path: |
            **/build/outputs/apk/**/*.apk
            **/build/reports/**/*
